# for development (uses docker-compose.yml and docker-compose.override.yml): 
# docker compose --env-file .env.dev up -d  
# for production (uses docker-compose.yml and docker-compose.prod.yml)
# docker compose --env-file .env.prod -f docker-compose.yml -f docker-compose.prod.yml up -d

version: "3.9"
services:
  web:
    depends_on:
      - api
    ports:
      - "$WEB_PORT:$WEB_PORT"
    environment:
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
    build: ./web
  api:
    depends_on:
      - db
    ports:
      - "$API_PORT:$API_PORT"
    environment:
      - DB_TYPE=$DB_TYPE
      - DB_USER=$DB_USER
      - DB_PASS=$DB_PASS
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - WEB_PORT=$WEB_PORT
      - API_PORT=$API_PORT
    build: ./api
  db:
    image: postgres:14.5
    restart: always
    ports:
      - "$DB_PORT:$DB_PORT"
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASS
    volumes:
      - db-vol:/var/lib/postgresql/data
volumes:
  db-vol:
